services:
  # Сервис бэка
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Проброс порта наружу
    environment:
      - MAX_FILE_SIZE=10485760 # Максимальный размер файла
      - MAX_TOTAL_SIZE=52428800 # Максимальный общий размер
      - FILE_TTL=600 # Время жизни файлов в хранилище
      - CLEANUP_INTERVAL=300 # Интервал очистки хранилища
      - ALLOWED_ORIGINS=* # Разрешенные origins
    restart: unless-stopped # Автоматически перезапускаться при падении

  # Сервис для разработки фронта
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app # Монтирование кода фронта
    ports:
      - "3001:3001" # Порт для разработки фронта
    command: sh -c "npm install && npx @tailwindcss/cli -i ./input.css -o ./style.css --watch & npx http-server -p 3001 -a 0.0.0.0 --verbose" # Устанавка зависимостей + запуск в dev-mode
    environment:
      - HOST=0.0.0.0 # Разрешить доступ с любого хоста
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
    tty: true # Предотвратить остановку контейнера
    stdin_open: true

# Сеть для улучшения коммуникации между сервисами
networks:
  default:
    name: code-merger-network
    driver: bridge
