basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      details:
        type: string
      error:
        type: string
    type: object
  handler.MergeRequest:
    properties:
      file_ids:
        items:
          type: string
        type: array
      file_renames:
        additionalProperties:
          type: string
        type: object
      output_filename:
        type: string
    type: object
  handler.UploadResponse:
    properties:
      file_ids:
        description: Массив идентификаторов загруженных файлов
        items:
          type: string
        type: array
      message:
        description: Сообщение о результате операции
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для объединения текстовых файлов.
  title: code-merger API
  version: 1.0.0
paths:
  /api/merge:
    post:
      consumes:
      - application/json
      description: Объединяет ранее загруженные файлы в один текстовый файл с соблюдением
        правил форматирования
      parameters:
      - description: Параметры объединения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.MergeRequest'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Объединенный файл
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Объединение загруженных файлов
      tags:
      - Processing
  /api/upload:
    post:
      consumes:
      - multipart/form-data
      description: Принимает один или несколько файлов для последующего объединения.
        Проверяет расширения и размер файлов.
      parameters:
      - description: Массив файлов для загрузки
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UploadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Загрузка файлов для обработки
      tags:
      - Files
swagger: "2.0"
